### ISSUE TITLE
Request: Server status

### ISSUE THREAD

**Issue by shadow7483147** [OPROSVOs/frensync#1]
When opening the settings panel (or a button in the settings), the script should ping or test all known servers to check their status. This will show the user which servers they are syncing to and that they are working correctly.

**Comment by OPROSVOs** [comment]
Thats a good idea.
Implemented that in version 0.1.4 like that:
![grafik](https://user-images.githubusercontent.com/19379091/148251387-8eabd71c-0cef-4b61-836f-7011df564f4c.png)

There is now an .json in the /server which contains all the server information and settings. The format is still a draft.
This .json is now used in the client instead of the previous hardcoded URLs.
And these can be iterated and checked.

Thie idea is to run two servers by two people later on for better reliability, if the original server stays like that.
